name: Generate UML

on:
  push:
    branches:
      - main

jobs:
  generate-uml:
    name: Generate UML
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate PlantUML file
        run: |
          echo "@startuml" > workflow.uml
          echo "!include <filename>" >> workflow.uml # If you have any external files included
          echo "skinparam monochrome true" >> workflow.uml # Change the theme to monochrome
          echo "start" >> workflow.uml
          echo ":Checkout code;" >> workflow.uml
          echo ":Install dependencies;" >> workflow.uml
          # Add more steps as needed
          echo ":Notify no build required;" >> workflow.uml
          echo "stop" >> workflow.uml
          echo "@enduml" >> workflow.uml

      - name: Install PlantUML
        run: sudo apt-get install -y plantuml

      - name: Generate UML image
        run: plantuml workflow.uml
        # Optionally, you can add the following line to save the generated image to a specific file name
        # run: plantuml -tpng workflow.uml -o output.png

      - name: Commit and push UML file
        if: always()
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update UML diagram"
          file_pattern: "*.png" # Adjust this pattern based on the format of your generated UML image file
