name: Generate UML

on:
  push:
    branches:
      - main

jobs:
  generate-uml:
    name: Generate UML
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate UML file
        run: |
          cat <<EOF > workflow.uml
          @startuml

          start

          :Checkout code;
          :Install dependencies;

          if (Build required?) then (yes)
            :Run unit tests;
            if (Tests pass?) then (yes)
              :Run linter;
              if (Lint pass?) then (yes)
                :Build Docker image;
                :Push Docker image;
                if (Deploy to Staging?) then (yes)
                  :Deploy to Staging;
                  if (Smoke tests pass?) then (yes)
                    :Promote to Production;
                    :Clean up resources;
                  else (no)
                    :Notify failure;
                  endif
                else (no)
                  :Notify no deployment;
                endif
              else (no)
                :Notify lint failure;
              endif
            else (no)
              :Notify test failure;
            endif
          else (no)
            :Notify no build required;
          endif

          stop

          @enduml
          EOF

      - name: Install PlantUML
        run: sudo apt-get install -y plantuml

      - name: Generate UML image
        run: plantuml workflow.uml

      - name: Commit and push UML file
        if: always()
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update UML diagram"
          file_pattern: "*.png" # Adjust this pattern based on the format of your generated UML image file
